services:
  database:
    image: postgres:18
    container_name: flights_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flights
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer:latest
    container_name: adminer
    restart: unless-stopped
    ports:
      - "8089:8080"
    environment:
      ADMINER_DEFAULT_SERVER: database
    depends_on:
      - database

volumes:
  postgres_data: